name: Java CI

permissions:
  contents: write

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -ntp install
      - run: mkdir staging && cp drools-lsp-server/target/drools-lsp-server-jar-with-dependencies.jar staging

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x

      - name: Package VS Code Extension
        working-directory: ./client
        run: |
          npm ci
          npm run pack:dev
          cp dist/*.vsix ../staging/

      - uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0" # v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            staging/*.jar
            staging/*.vsix
